package com.tdl.guaranteedsavings.dto

data class ApplicationPaymentDTO (
    val paymentId:String,
    val orderId:String,
    val orderRetrialId:String,
    val merchantId:String,
    val tPayCustomerId:String,
    val tcpNum:String,
    val customerName:String,
    val merchantName:String,
    val terminalType:String,
    val billCategory:String,
    val status:String,
    val subStatus:String,
    val failureReason:String,
    val totalCartAmount:String,
    val totalCartFinalAmt:String,
    val totalTaxAmt:String,
    val storeCode:String,
    val prepaidAmt:String,
    val typeOfRequest:String,
    val callBackUrl:String,
    val timeout:String,
    val timeRemaining:String,
    val tdlOrderTransactId:String,
    val reversalId:String,
    val tataPayPwaUrl:String,
    val errorInfo:String,
    val warningInfo:String,
    val statusInfo:String,
    val createdByUser:String,
    val createdByDate:String,
    val modifiedByUser:String,
    val modifiedByDate:String
)