package com.tdl.guaranteedsavings.dto

data class InsurancePolicyDTO(

    val id: String,
    val applicationNo: String,
    val basePremiumAmount: String,
    val certificateNumber: String,
    val cgst: String,
    val customerHash: String,
    val igst: String,
    val inceptionDate: String,
    val incomeDuration: String,
    val incomeFrequency: String,
    val incomeType: String,
    val insurancePolicyId: String,
    val insurerId: String,
    val investmentFrequency: String,
    val isIntraState: String,
    val isSmoker: String,
    val otp: String,
    val otpRefid: String,
    val paymentMode: String,
    val planId: String,
    val policyActivated: String,
    val policyEnddate: String,
    val policyNumber: String,
    val policyPayTerm: String,
    val policyPdfUrl: String,
    val policyStartDate: String,
    val policyStatus: String,
    val policyTerm: String,
    val sgst: String,
    val sumAssuredAmount: String,
    val tataDiscount: String,
    val taxAmount: String,
    val remark: String,
    val createdByDate: String,
    val createdByUser: String,
    val modifiedByDate: String,
    val modifiedByUser: String,
)
